name: Fetch Latest Tweets
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *' 
  workflow_dispatch: # Allows you to manually run the job for testing

jobs:
  update-readme-with-twitter:
    name: Update this repo's README with latest tweets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "TWEETS-LIST"
          feed_list: "https://xcancel.com/jigar_o/rss"
          max_post_count: 3 # Number of tweets to show
